### ISSUE TITLE
Can't run without -user on Ubuntu 10.4

### ISSUE THREAD

**Issue by deployingjruby** [trinidad/trinidad_init_services#16]
when i run jsvc  as `sudo -u myuser jsvc ...` i get this error:

```
set_caps: failed to set capabilities
check that your kernel supports capabilities
set_caps(CAPS) failed
Service exit with a return value of 4
```

If I run it like this `jsvc -user myuser ....` it works.

Unless there is something obvious i'm missing, i'd like to add the -user back in as an optional argument (even if it's just flipped on with an ENV var instead of through the config file or command-line).

Thoughts?

```
$ uname -a
Linux lucid64 2.6.32-33-server #70-Ubuntu SMP Thu Jul 7 22:28:30 UTC 2011 x86_64 GNU/Linux
```

see also: https://github.com/trinidad/trinidad_init_services/pull/12

**Comment by kares** [comment]
that's interesting cause for me (on Debian x64 and Ubuntu x86) and another user also confirmed (on Ubuntu) that `jsvc -user` ain't working ... we'd like to have by default the option that works for most users and `sudo` seemed fine.

btw. your issue is mentioned in the FAQ: http://commons.apache.org/daemon/faq.html have you tried fixing it ?

**Comment by jkutner** [comment]
I really don't want to mess with my kernel config (nor have I been able to get that working).  I'm trying to keep my setup as simple as possible.  I'll keep hacking around with it before merging this in.

**Comment by jkutner** [comment]
just do this, duh :P

JSVC_ARGS_EXTRA="-user myuser" /etc/init.d/trinidad start
